### ISSUE TITLE
[Feature Request] Docker | Containerized support 

### ISSUE THREAD

**Issue by Freebase394** [hestiacp/hestiacp#1101]
Hi, I will try to help in the best possible way.
I must say that the script should work very well for x86x64 virtualized environments, but as I had the opportunity to test, and I also have more tests running, but the script does not work at least for Debian 10 in Docker environments.

NOTE:  <s>the script got stuck in "it will take between 10 to 15 minutes"<s> 
I still have to leave print, images, outputs, configuration tests, but as far as I am concerned I will "Try to help" to make this available and implemented for docker environments.

Milestone wanted: 
Debian 9 -->WIP
Debian 10 -->Tested and not Working...
Ubuntu 16.04 LTS -->WIP
Ubuntu 18.04 LTS--> PROBLEMS with Packages ... [WIP]
Ubuntu 20.04 LTS-->WIP

Work in progress...

**Comment by luizjr** [comment]
Dockerize this is a great idea!

**Comment by Pleskan** [comment]
I don't think so, it's strongly depends on your needs, your skills and existing infrastucture.
Advantage for one usecase might be non-applicable for the others or even became a disaster.
There is no **Silver Bullet**

**Comment by jaapmarcus** [comment]
Remove all the pipes to /dev/null and try again. I think it stuck of some where around the apt-get update sequince 

https://github.com/hestiacp/hestiacp/blob/90f5e247eb61fe66c4b6981de17a380f2e8a8ad5/install/hst-install-debian.sh#L825-L848

**Comment by Freebase394** [comment]
### Progress made

- [X] Enable panel installation in Docker environments

- [ ] Test the environments 


# Milestone Reached
- [ ] Debian 9 -->WIP

- [X] Debian 10 -->Sucess

- [ ] Ubuntu 16.04 LTS -->WIP

- [X] Ubuntu 18.04 LTS--> Sucess

- [X] Ubuntu 20.04 LTS--> Sucess

- [X] CentOS 7 --> 👍 Ready 

WARNING: for those who already have practice and independent knowledge with the docker these procedures will be very easy to do, but for the vast majority like me I had to dig deeper.
The next step will be to run tests and include the proper documentation for all of these procedures!

**Comment by Freebase394** [comment]
### Initial Stage
- [X]  https://github.com/hestiacp/hestiacp/issues/1140

**Comment by Freebase394** [comment]
![image](https://user-images.githubusercontent.com/19652056/93769104-45dddc00-fc12-11ea-85e1-d3ee85be390a.png)

Somethings...

**Comment by ghost** [comment]
We have discussed this internally, and due to time and resource constraints this is not something we will be able to solve at this time -- however if you wish to continue working on this and submit a pull request, we will be more than happy to review.
